### ISSUE TITLE
Todo against the "form-components" branch

### ISSUE THREAD

**Issue by notmessenger** [ember-forge/ember-forge-ui#50]

**Comment by notmessenger** [comment]
Items remaining

- [ ] [4.10.3](https://html.spec.whatwg.org/multipage/index.html) - need to handle validation, submission, etc
- [ ] [4.10.5](https://html.spec.whatwg.org/multipage/index.html) - The input element
  - [ ] image uploads functionality - https://styles.clickfunnels.com/ui-components/forms
- [ ] [4.10.7](https://html.spec.whatwg.org/multipage/index.html) - The select element - ember-power-select?
- [ ] [4.10.9](https://html.spec.whatwg.org/multipage/index.html) - The optgroup element
- [ ] [4.10.10](https://html.spec.whatwg.org/multipage/index.html) - The option element
- [ ] [4.10.14](https://html.spec.whatwg.org/multipage/index.html) - The progress element - put in root - even add to form?   can be associated with a label element
- [ ] [4.10.15](https://html.spec.whatwg.org/multipage/index.html) - The meter element - put in root - even add to form?  can be associated with a label element
- [ ] [4.8.7](https://html.spec.whatwg.org/multipage/index.html) - The object element
- [ ] [4.10.13](https://html.spec.whatwg.org/multipage/index.html) - The output element   can be associated with a label element
- [ ] [4.10.8](https://html.spec.whatwg.org/multipage/index.html) - The fatalist element
- [ ] type ahead field
- [ ] bubbles = true/false on components to keep events from bubbling?  see sl-ember-components button
- [ ] store data in local storage until a successful save

**Comment by notmessenger** [comment]
**ARIA**

* https://github.com/martndemus/ember-form-for/issues/48#issuecomment-223773427
* https://w3c.github.io/html-aria/
* https://w3c.github.io/aria/html-aam/html-aam.html
